export const data = [
	{
		id: 0,
		file: 'гроза мать ее.mp3',
		name: 'Гроза, мать ее',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 1,
		file: 'ведьмак (стих).mp3',
		name: 'Стих про ведьмака',
		author: 'Крестьянин',
		duration: '00:09',
		explicit: false,
	},
	{
		id: 2,
		file: 'веди себя прилично ведьмак.mp3',
		name: 'Веди себя прилично',
		author: 'Стражник',
		duration: '00:04',
		explicit: true,
	},
	{
		id: 3,
		file: 'я пацифист.mp3',
		name: 'Я пацифист',
		author: 'Крестьянин',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 4,
		file: 'смех.mp3',
		name: 'Смех',
		author: 'Крестьянин',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 5,
		file: 'бегут неуклюжие пешеходы по лужам.mp3',
		name: 'Бегут неуклюжие пешеходы по лужам',
		author: 'Крестьянин',
		duration: '00:06',
		explicit: false,
	},
	{
		id: 6,
		file: 'бедняжечка.mp3',
		name: 'Бедняжечка',
		author: 'Крестьянка',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 7,
		file: 'пам парам пам пам пам парам пам пам.mp3',
		name: 'Пам парам пам',
		author: 'Бандит',
		duration: '00:11',
		explicit: false,
	},
	{
		id: 8,
		file: 'веди себя прилично хулиган.mp3',
		name: 'Веди себя прилично, хулиган',
		author: 'Крестьянин',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 9,
		file: 'Приветствую).mp3',
		name: 'Приветствую)',
		author: 'Крестьянин',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 10,
		file: 'глаза видят уши слышат уста молчат.mp3',
		name: 'Глаза видят, уши слышат, уста молчат',
		author: 'Крестьянин',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 11,
		file: 'глазища у тебя змеиные а язык.mp3',
		name: 'Глазища у тебя змеиные',
		author: 'Крестьянка',
		duration: '00:05',
		explicit: true,
	},
	{
		id: 12,
		file: 'да благоволит тебе фортуна.mp3',
		name: 'Да благоволит тебе фортуна',
		author: 'Крестьянин',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 13,
		file: 'свестит мелодию.mp3',
		name: 'Свестит мелодию',
		author: 'Крестьянин',
		duration: '00:13',
		explicit: false,
	},
	{
		id: 14,
		file: 'И что такого.mp3',
		name: 'И что такого',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 15,
		file: 'Я хочу помочь нильфгаардской женщине.mp3',
		name: 'Я хочу помочь нильфгаардской женщине',
		author: 'Геральт',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 16,
		file: 'Похоже дождь собирается.mp3',
		name: 'Похоже, дождь собирается',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 17,
		file: 'Дождь.mp3',
		name: 'Дождь',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 18,
		file: 'Жарко.mp3',
		name: 'Жарко',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 19,
		file: 'Ветер.mp3',
		name: 'Ну и ветер',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 20,
		file: 'Погода в самый раз.mp3',
		name: 'Погода в самый раз',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 21,
		file: 'Распогодилось.mp3',
		name: 'Распогодилось',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 22,
		file: 'Снег пошел.mp3',
		name: 'Снег пошел',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 23,
		file: 'Холодает.mp3',
		name: 'Холодает',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 24,
		file: 'Похоже шторм будет.mp3',
		name: 'Похоже, шторм будет',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 25,
		file: 'Вот сука.mp3',
		name: 'Вот сука',
		author: 'Геральт',
		duration: '00:02',
		explicit: true,
	},
	{
		id: 26,
		file: 'Зараза.mp3',
		name: 'Зараза',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 27,
		file: 'Иди сюда.mp3',
		name: 'Иди, иди сюда',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 28,
		file: 'Мертв.mp3',
		name: 'Мертв',
		author: 'Геральт',
		duration: '00:02',
		explicit: true,
	},
	{
		id: 29,
		file: 'Не стоит.mp3',
		name: 'Не стОит',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 30,
		file: 'Неплохо.mp3',
		name: 'Неплохо',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 31,
		file: 'Никак вы, блядь, не научитесь.mp3',
		name: 'Никак вы, бл*дь, не научитесь',
		author: 'Геральт',
		duration: '00:03',
		explicit: true,
	},
	{
		id: 32,
		file: 'Давай.mp3',
		name: 'Давай',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 33,
		file: 'Ну что паскуда.mp3',
		name: 'Ну что, паскуда',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 34,
		file: 'Ох и гнусный же ты.mp3',
		name: 'Ох и гнусный же ты',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 35,
		file: 'Покончим с этим.mp3',
		name: 'Покончим с этим',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 36,
		file: 'Пора заканчивать.mp3',
		name: 'Пора заканчивать',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 37,
		file: 'Сдохни.mp3',
		name: 'Сдохни!',
		author: 'Геральт',
		duration: '00:02',
		explicit: true,
	},
	{
		id: 38,
		file: 'У тебя сегодня плохой день.mp3',
		name: 'У тебя сегодня плохой день',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 39,
		file: 'и слушать об этом не хочу.mp3',
		name: 'И слушать об этом не хочу',
		author: 'Крестьянка',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 40,
		file: 'куда спешишь удалец.mp3',
		name: 'Куда спешишь, удалец',
		author: 'Крестьянка',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 41,
		file: 'мой ответ нет.mp3',
		name: 'Мой ответ - нет',
		author: 'Крестьянка',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 42,
		file: 'морду у тебя перекосило.mp3',
		name: 'Морду у тебя перекосило',
		author: 'Крестьянка',
		duration: '00:06',
		explicit: false,
	},
	{
		id: 43,
		file: 'мяу мр.mp3',
		name: 'Мяу',
		author: 'Крестьянка',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 44,
		file: 'ну я и влажная.mp3',
		name: 'Ну я и влажная',
		author: 'Крестьянка',
		duration: '00:05',
		explicit: true,
	},
	{
		id: 45,
		file: 'Поет.mp3',
		name: 'Поет',
		author: 'Крестьянка',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 46,
		file: 'привет мрачненький.mp3',
		name: 'Привет, мрачненький',
		author: 'Крестьянка',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 47,
		file: 'Смех (ж).mp3',
		name: 'Смех',
		author: 'Крестьянка',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 48,
		file: 'хорошо сегодня выглядишь.mp3',
		name: 'Хорошо сегодня выглядишь',
		author: 'Крестьянка',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 49,
		file: 'Сгниешь в подземелье паршивец.mp3',
		name: 'Сгниешь в подземелье, паршивец',
		author: 'Стражник',
		duration: '00:04',
		explicit: true,
	},
	{
		id: 50,
		file: 'сдавайся.mp3',
		name: 'Сдавайся',
		author: 'Стражник',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 51,
		file: 'сдохни (с).mp3',
		name: 'Сдохни',
		author: 'Стражник',
		duration: '00:02',
		explicit: true,
	},
	{
		id: 52,
		file: 'я буду за тобой приглядывать белоголовый.mp3',
		name: 'Я буду за тобой приглядывать, белоголовый',
		author: 'Стражник',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 53,
		file: 'спокойней, минутку, минутку.mp3',
		name: 'Cпокойней, минутку, минутку',
		author: 'Стражник',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 54,
		file: 'Таких как ты вообще в новиград впускать нельзя.mp3',
		name: 'Таких как ты вообще в новиград впускать нельзя',
		author: 'Стражник',
		duration: '00:05',
		explicit: true,
	},
	{
		id: 55,
		file: 'ты труп труп.mp3',
		name: 'Ты труп труп',
		author: 'Стражник',
		duration: '00:03',
		explicit: true,
	},
	{
		id: 56,
		file: 'хватит хватит.mp3',
		name: 'Хватит, хватит',
		author: 'Стражник',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 57,
		file: 'ААААААА.mp3',
		name: 'ААААААА',
		author: 'Бандит',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 58,
		file: 'ах ты хер.mp3',
		name: 'Ах ты хер',
		author: 'Бандит',
		duration: '00:02',
		explicit: true,
	},
	{
		id: 59,
		file: 'Давай двигай.mp3',
		name: 'Давай, двигай',
		author: 'Бандит',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 60,
		file: 'Кашель.mp3',
		name: 'Кашель',
		author: 'Бандит',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 61,
		file: 'хватит хватит.mp3',
		name: 'Хватит, хватит',
		author: 'Бандит',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 62,
		file: 'Мы не справимся.mp3',
		name: 'Мы не справимся',
		author: 'Бандит',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 63,
		file: 'не дури.mp3',
		name: 'Не дури',
		author: 'Бандит',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 64,
		file: 'нет (умирает).mp3',
		name: 'Нет (умирает)',
		author: 'Бандит',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 65,
		file: 'нет прошу нет.mp3',
		name: 'Нет, прошу, нет',
		author: 'Бандит',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 66,
		file: 'боги спасите.mp3',
		name: 'Боги спасите',
		author: 'Крестьянин',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 67,
		file: 'плевок.mp3',
		name: 'Плевок',
		author: 'Бандит',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 68,
		file: 'Подозрительно ты выглядишь приблуда.mp3',
		name: 'Подозрительно ты выглядишь, приблуда',
		author: 'Бандит',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 69,
		file: 'Смеется.mp3',
		name: 'Смеется',
		author: 'Бандит',
		duration: '00:06',
		explicit: false,
	},
	{
		id: 70,
		file: 'тебе конец.mp3',
		name: 'Тебе конец',
		author: 'Бандит',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 71,
		file: 'это же байда бааайда.mp3',
		name: 'Это же байда, бааайда',
		author: 'Бандит',
		duration: '00:07',
		explicit: false,
	},
	{
		id: 72,
		file: 'лололололо.mp3',
		name: 'Лололололо',
		author: 'Крестьянин',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 73,
		file: 'на костёр пойдешь чертов сын.mp3',
		name: 'На костёр пойдешь, чертов сын',
		author: 'Крестьянин',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 74,
		file: 'подайте крон.mp3',
		name: 'Подайте крону',
		author: 'Крестьянин',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 75,
		file: 'вялый ты какой то тухлого мяса наелся.mp3',
		name: 'Вялый ты какой-то',
		author: 'Крестьянин',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 76,
		file: 'Приветствую, честь имею.mp3',
		name: 'Приветствую, честь имею',
		author: 'Крестьянин',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 77,
		file: 'спасите.mp3',
		name: 'Спасите',
		author: 'Крестьянин',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 78,
		file: 'Хочешь я тебя обниму.mp3',
		name: 'Хочешь я тебя обниму?',
		author: 'Крестьянин',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 79,
		file: 'хер оторвет.mp3',
		name: 'Хер оторвет',
		author: 'Крестьянин',
		duration: '00:06',
		explicit: true,
	},
	{
		id: 80,
		file: 'Хохоххо мамочки.mp3',
		name: 'Мамочки!',
		author: 'Крестьянин',
		duration: '00:04',
		explicit: false,
	},

	{
		id: 81,
		file: 'бывай.mp3',
		name: 'Бывай',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
]
