export const data = [
	{
		id: 0,
		file: 'гроза мать ее.mp3',
		name: 'Гроза, мать ее',
		author: 'Геральт',
		duration: '00:01',
		explicit: false,
	},
	{
		id: 1,
		file: 'ведьмак (стих).mp3',
		name: 'Стих про ведьмака',
		author: 'НПС',
		duration: '00:09',
		explicit: false,
	},
	{
		id: 2,
		file: 'веди себя прилично ведьмак.mp3',
		name: 'Веди себя прилично',
		author: 'НПС',
		duration: '00:04',
		explicit: true,
	},
	{
		id: 3,
		file: 'я пацифист.mp3',
		name: 'Я пацифист',
		author: 'НПС',
		duration: '00:01',
		explicit: false,
	},
	{
		id: 4,
		file: 'смех.mp3',
		name: 'Смех',
		author: 'НПС',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 5,
		file: 'бегут неуклюжие пешеходы по лужам.mp3',
		name: 'Бегут неуклюжие пешеходы по лужам',
		author: 'НПС',
		duration: '00:06',
		explicit: false,
	},
	{
		id: 6,
		file: 'бедняжечка.mp3',
		name: 'Бедняжечка',
		author: 'НПС',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 7,
		file: 'боги спасите.mp3',
		name: 'Боги спасите',
		author: 'НПС',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 8,
		file: 'веди себя прилично хулиган.mp3',
		name: 'Веди себя прилично, хулиган',
		author: 'НПС',
		duration: '00:04',
		explicit: false,
	},
	{
		id: 9,
		file: 'вялый ты какой то тухлого мяса наелся.mp3',
		name: 'Вялый ты какой-то',
		author: 'НПС',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 10,
		file: 'глаза видят уши слышат уста молчат.mp3',
		name: 'Глаза видят, уши слышат, уста молчат',
		author: 'НПС',
		duration: '00:05',
		explicit: false,
	},
	{
		id: 11,
		file: 'глазища у тебя змеиные а язык.mp3',
		name: 'Глазища у тебя змеиные',
		author: 'НПС',
		duration: '00:05',
		explicit: true,
	},
	{
		id: 12,
		file: 'да благоволит тебе фортуна.mp3',
		name: 'Да благоволит тебе фортуна',
		author: 'НПС',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 13,
		file: 'бывай.mp3',
		name: 'Бывай',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 14,
		file: 'И что такого.mp3',
		name: 'И что такого',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 15,
		file: 'Я хочу помочь нильфгаардской женщине.mp3',
		name: 'Я хочу помочь нильфгаардской женщине',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 16,
		file: 'Похоже дождь собирается.mp3',
		name: 'Похоже, дождь собирается',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 17,
		file: 'Дождь.mp3',
		name: 'Дождь',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 18,
		file: 'Жарко.mp3',
		name: 'Жарко',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 19,
		file: 'Похоже дождь собирается.mp3',
		name: 'Похоже, дождь собирается',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 20,
		file: 'Дождь.mp3',
		name: 'Дождь',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 21,
		file: 'Ветер.mp3',
		name: 'Ну и ветер',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 22,
		file: 'Погода в самый раз.mp3',
		name: 'Погода в самый раз',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 23,
		file: 'Распогодилось.mp3',
		name: 'Распогодилось',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 24,
		file: 'Снег пошел.mp3',
		name: 'Снег пошел',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 25,
		file: 'Холодает.mp3',
		name: 'Холодает',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 26,
		file: 'Похоже шторм будет.mp3',
		name: 'Похоже, шторм будет',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 27,
		file: 'блять.mp3',
		name: 'Бл*ть',
		author: 'Геральт',
		duration: '00:01',
		explicit: true,
	},
	{
		id: 28,
		file: 'Вот сука.mp3',
		name: 'Вот сука',
		author: 'Геральт',
		duration: '00:02',
		explicit: true,
	},
	{
		id: 29,
		file: 'Зараза.mp3',
		name: 'Зараза',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 30,
		file: 'Иди сюда.mp3',
		name: 'Иди, иди сюда',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 31,
		file: 'Мертв.mp3',
		name: 'Мертв',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 32,
		file: 'Не стоит.mp3',
		name: 'Не стОит',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 33,
		file: 'Неплохо.mp3',
		name: 'Неплохо',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 34,
		file: 'Никак вы, блядь, не научитесь.mp3',
		name: 'Никак вы, бл*дь, не научитесь',
		author: 'Геральт',
		duration: '00:03',
		explicit: true,
	},
	{
		id: 35,
		file: 'Ну давай.mp3',
		name: 'Ну давай!',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 36,
		file: 'Давай.mp3',
		name: 'Давай',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 37,
		file: 'Ну что паскуда.mp3',
		name: 'Ну что, паскуда',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 38,
		file: 'Ох и гнусный же ты.mp3',
		name: 'Ох и гнусный же ты',
		author: 'Геральт',
		duration: '00:03',
		explicit: false,
	},
	{
		id: 39,
		file: 'Покончим с этим.mp3',
		name: 'Покончим с этим',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 40,
		file: 'Пора заканчивать.mp3',
		name: 'Пора заканчивать',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 41,
		file: 'Сдохни.mp3',
		name: 'Сдохни!',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
	{
		id: 42,
		file: 'У тебя сегодня плохой день.mp3',
		name: 'У тебя сегодня плохой день',
		author: 'Геральт',
		duration: '00:02',
		explicit: false,
	},
]
